In [5]:
#Task 01
import numpy as np


arr = np.array([[0, 1], [2, 3]])

print("Original flattened array:")
print(arr)


flatarr = arr.flatten()


max = flatarr.max()
min = flatarr.min()


print("Maximum value of the above flattened array:", max)
print("Minimum value of the above flattened array:", min)

Original flattened array:
[[0 1]
 [2 3]]
Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


In [4]:
#Lab Task 02
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)

print("3x3 Matrix with values from 2 to 10:")
print(matrix)


3x3 Matrix with values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
#Lab Task 03
import numpy as np

arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

float_arr = arr.astype(float)
print("Array converted to a float type:", float_arr)


Original array: [1 2 3 4]
Array converted to a float type: [1. 2. 3. 4.]


In [2]:
#Lab Task 04
import numpy as np

M1 = np.array([[5, 5],
               [1, 2]])

M2 = np.array([[0, 1],
               [1, 0]])

result = np.dot(M1, M2)

transpose_result = result.T

print("Matrix M1:")
print(M1)

print("\nMatrix M2:")
print(M2)

print("\nResult of M1 x M2:")
print(result)

print("\nTranspose of the Result:")
print(transpose_result)



Matrix M1:
[[5 5]
 [1 2]]

Matrix M2:
[[0 1]
 [1 0]]

Result of M1 x M2:
[[5 5]
 [2 1]]

Transpose of the Result:
[[5 2]
 [5 1]]


In [1]:
#Lab Task 05
import numpy as np

A = np.array([
    [6, 1, 1, 3],
    [4, -2, 5, 1],
    [2, 8, 7, 6],
    [3, 1, 9, 7]
])

print("Original Matrix:")
print(A)

A_inv = np.linalg.inv(A)

print("\nInverse of the Matrix:")
print(A_inv)


Original Matrix:
[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]

Inverse of the Matrix:
[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
